[package]
name = "jpeg-encoder-wasm"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
jpeg-encoder = { path = "..", default-features = false, features = ["wasm-bindgen"] }

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
